-- MySQL Script generated by MySQL Workbench
-- Mon Apr 12 19:42:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aluguel_carros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aluguel_carros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aluguel_carros` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `aluguel_carros` ;

-- -----------------------------------------------------
-- Table `aluguel_carros`.`agente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluguel_carros`.`agente` (
  `id_usuario` INT NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `id_user_agente`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `aluguel_carros`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aluguel_carros`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluguel_carros`.`aluguel` (
  `id` INT NOT NULL,
  `contrato` VARCHAR(45) NOT NULL,
  `proprietario` INT NOT NULL,
  `agente` INT NOT NULL,
  `automovel` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_cliente_idx` (`proprietario` ASC) VISIBLE,
  INDEX `id_agente_idx` (`agente` ASC) VISIBLE,
  INDEX `id_automovel_idx` (`automovel` ASC) VISIBLE,
  CONSTRAINT `id_agente`
    FOREIGN KEY (`agente`)
    REFERENCES `aluguel_carros`.`agente` (`id_usuario`),
  CONSTRAINT `id_automovel`
    FOREIGN KEY (`automovel`)
    REFERENCES `aluguel_carros`.`automovel` (`id`),
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`proprietario`)
    REFERENCES `aluguel_carros`.`cliente` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aluguel_carros`.`automovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluguel_carros`.`automovel` (
  `id` INT NOT NULL,
  `matricula` INT NOT NULL,
  `ano` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aluguel_carros`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluguel_carros`.`cliente` (
  `id_usuario` INT NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `profissao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `aluguel_carros`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aluguel_carros`.`empregador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluguel_carros`.`empregador` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `id_user_empregador`
    FOREIGN KEY (`id_user`)
    REFERENCES `aluguel_carros`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aluguel_carros`.`rendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluguel_carros`.`rendimento` (
  `id` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `id_user_rendimento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_idx` (`id_user_rendimento` ASC) VISIBLE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user_rendimento`)
    REFERENCES `aluguel_carros`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aluguel_carros`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluguel_carros`.`usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
